In [1]:
import os
import sys
sys.path.append(os.path.abspath(".."))


In [2]:
from A11M.models.rnn import RNNCell

In [3]:
rnn = RNNCell(2, 3)

In [4]:
print("WH : ", rnn.Whh)

WH :  Parameter containing:
tensor([[ 0.6355,  0.5220, -1.1094],
        [ 1.1472,  0.4480,  0.8112],
        [ 0.6123,  0.3352,  0.7567]], requires_grad=True)


In [5]:
print("WX : ", rnn.Wxh)

WX :  Parameter containing:
tensor([[-1.0574, -2.3983, -0.5628],
        [-0.4302,  0.2227, -0.1312]], requires_grad=True)


In [6]:
# Hidden state
import torch

X = torch.tensor([
    [1.0, 0.0],
    [0.1, 0.2],
], dtype=torch.float32)

h_prev = torch.tensor([
    [1.0, 2.0, 0.0],
    [0.2, 0.3, 1.0]
], dtype=torch.float32)

h = rnn.forward(X, h_prev)
print("H : ", h)

H :  tensor([[ 0.9538, -0.7532, -0.0498],
        [ 0.7123,  0.3616,  0.6016]], grad_fn=<TanhBackward0>)


In [7]:
t = torch.zeros((2, 3))
batch_size, seq_len = t.shape
print('Batch size : ', batch_size)
print('seq_len : ', seq_len)

Batch size :  2
seq_len :  3


In [8]:
t = torch.tensor([
    [1.0, 2.0, 0.0],
    [0.2, 0.3, 1.0]
], dtype=torch.float32)
batch_size, seq_len = t.shape
print('Batch size : ', batch_size)
print('seq_len : ', seq_len)

Batch size :  2
seq_len :  3


In [9]:
A = torch.tensor([
    [1, 3],
    [2, 4]
], dtype=torch.float32)

B = torch.tensor([
    [2, 3],
    [1, 4]
], dtype=torch.float32)

A @ B

tensor([[ 5., 15.],
        [ 8., 22.]])

In [10]:
A = torch.tensor([
    [1, 2, 3],
    [4, 5, 6]
], dtype=torch.float32)

B = torch.tensor([
    [1, 0, 1],
    [0, 1, 1],
    [1, 0, 1]
], dtype=torch.float32)

A @ B

tensor([[ 4.,  2.,  6.],
        [10.,  5., 15.]])

In [11]:
B = torch.randn(4, 6, 8) # (batch_size=4, seq_len=6, feature_size=8)
B = torch.randn(4, 6, 8) # (batch_size=4, seq_len=6, feature_size=8)
B[0]

tensor([[-0.1846,  1.3088, -0.4004, -0.8457,  1.1745,  0.4992, -0.1439,  0.9410],
        [-0.9479, -0.8124,  0.5035,  1.2562,  2.4195,  0.5881,  0.0090, -0.1859],
        [-0.4384,  0.8865, -0.1157,  1.6547, -1.7019,  0.0415, -1.1178,  1.8324],
        [ 0.1476, -0.0881, -0.3336,  0.1281, -0.8032,  2.3086,  0.3410, -0.3318],
        [-0.6989, -0.5936, -0.5627, -0.6626, -0.4219,  0.3564,  1.3520,  0.9595],
        [-0.3079, -0.0300,  1.0430, -0.3115,  1.0440,  0.8131,  0.4987, -1.1736]])

In [12]:
B[0, :, :]

tensor([[-0.1846,  1.3088, -0.4004, -0.8457,  1.1745,  0.4992, -0.1439,  0.9410],
        [-0.9479, -0.8124,  0.5035,  1.2562,  2.4195,  0.5881,  0.0090, -0.1859],
        [-0.4384,  0.8865, -0.1157,  1.6547, -1.7019,  0.0415, -1.1178,  1.8324],
        [ 0.1476, -0.0881, -0.3336,  0.1281, -0.8032,  2.3086,  0.3410, -0.3318],
        [-0.6989, -0.5936, -0.5627, -0.6626, -0.4219,  0.3564,  1.3520,  0.9595],
        [-0.3079, -0.0300,  1.0430, -0.3115,  1.0440,  0.8131,  0.4987, -1.1736]])

In [13]:
B[:, 0, :]

tensor([[-0.1846,  1.3088, -0.4004, -0.8457,  1.1745,  0.4992, -0.1439,  0.9410],
        [-0.8164,  2.0894, -0.2871,  1.3000, -1.2883, -0.3139, -1.7292,  0.1065],
        [ 1.0970,  0.4334,  0.3800,  1.1729, -0.2287, -1.7480, -2.8473, -0.4301],
        [ 0.7239, -0.7578, -0.0154,  0.5289,  1.0666, -2.1159, -0.0587,  0.3693]])

In [14]:
x = torch.randn(2, 3)
x

tensor([[-0.2784,  0.4375,  0.0459],
        [ 0.0066,  1.1939, -0.1885]])

In [15]:
torch.cat((x, x, x), dim=0)

tensor([[-0.2784,  0.4375,  0.0459],
        [ 0.0066,  1.1939, -0.1885],
        [-0.2784,  0.4375,  0.0459],
        [ 0.0066,  1.1939, -0.1885],
        [-0.2784,  0.4375,  0.0459],
        [ 0.0066,  1.1939, -0.1885]])

In [16]:
torch.cat((x, x, x), dim=1)

tensor([[-0.2784,  0.4375,  0.0459, -0.2784,  0.4375,  0.0459, -0.2784,  0.4375,
          0.0459],
        [ 0.0066,  1.1939, -0.1885,  0.0066,  1.1939, -0.1885,  0.0066,  1.1939,
         -0.1885]])

In [17]:
x3d = x.unsqueeze(0).repeat(4, 1, 1) # 4 batch
x3d

tensor([[[-0.2784,  0.4375,  0.0459],
         [ 0.0066,  1.1939, -0.1885]],

        [[-0.2784,  0.4375,  0.0459],
         [ 0.0066,  1.1939, -0.1885]],

        [[-0.2784,  0.4375,  0.0459],
         [ 0.0066,  1.1939, -0.1885]],

        [[-0.2784,  0.4375,  0.0459],
         [ 0.0066,  1.1939, -0.1885]]])

In [18]:
x3d = x.unsqueeze(0)
x3d[0][1]

tensor([ 0.0066,  1.1939, -0.1885])

In [19]:
x3d = x.unsqueeze(1)
x3d[1][0]

tensor([ 0.0066,  1.1939, -0.1885])

In [20]:
# Toy dataset
import torch.nn as nn
from A11M.models.rnn import RNN


text = "hello"
chars = sorted(set(text))
stoi = {c: i for i, c in enumerate(chars)}
itos = {i: c for c, i in stoi.items()}
vocab_size = len(chars)

def encode(s): return torch.tensor([stoi[c] for c in s], dtype=torch.long)
def decode(t): return ''.join([itos[int(i)] for i in t])

# Input/target
X = encode("hello").unsqueeze(0)      # shape: (1, 5)
Y = encode("elloh").unsqueeze(0)      # shape: (1, 5)

# Model and training
model = RNN(vocab_size, embed_size=8, hidden_size=16)
criterion = nn.CrossEntropyLoss()
optimizer = torch.optim.Adam(model.parameters(), lr=0.01)

for epoch in range(300):
    optimizer.zero_grad()
    logits = model(X)                         # (1, 5, vocab_size)
    loss = criterion(logits.view(-1, vocab_size), Y.view(-1))
    loss.backward()
    optimizer.step()

    if epoch % 50 == 0:
        pred = logits.argmax(dim=2).squeeze()
        print(f"[{epoch}] Loss: {loss.item():.4f} | Predicted: {decode(pred)}")

[0] Loss: 1.2183 | Predicted: lhlhh
[50] Loss: 0.0235 | Predicted: elloh
[100] Loss: 0.0095 | Predicted: elloh
[150] Loss: 0.0056 | Predicted: elloh
[200] Loss: 0.0038 | Predicted: elloh
[250] Loss: 0.0024 | Predicted: elloh


In [21]:
import requests


url = "https://raw.githubusercontent.com/karpathy/char-rnn/master/data/tinyshakespeare/input.txt"
text = requests.get(url).text
text = text[:10000]  # 10k characters for fast training
chars = sorted(set(text))
stoi = {ch: i for i, ch in enumerate(chars)}
itos = {i: ch for ch, i in stoi.items()}
vocab_size = len(chars)
def encode(s): return [stoi[c] for c in s]
def decode(t): return ''.join([itos[i] for i in t])

In [26]:
print(text)

First Citizen:
Before we proceed any further, hear me speak.

All:
Speak, speak.

First Citizen:
You are all resolved rather to die than to famish?

All:
Resolved. resolved.

First Citizen:
First, you know Caius Marcius is chief enemy to the people.

All:
We know't, we know't.

First Citizen:
Let us kill him, and we'll have corn at our own price.
Is't a verdict?

All:
No more talking on't; let it be done: away, away!

Second Citizen:
One word, good citizens.

First Citizen:
We are accounted poor citizens, the patricians good.
What authority surfeits on would relieve us: if they
would yield us but the superfluity, while it were
wholesome, we might guess they relieved us humanely;
but they think we are too dear: the leanness that
afflicts us, the object of our misery, is as an
inventory to particularise their abundance; our
sufferance is a gain to them Let us revenge this with
our pikes, ere we become rakes: for the gods know I
speak this in hunger for bread, not in thirst for revenge.



In [22]:
sequence_length = 40
step = 3  # stride
X, Y = [], []
for i in range(0, len(text) - sequence_length, step):
    chunk = text[i:i+sequence_length]
    target = text[i+1:i+sequence_length+1]
    X.append(encode(chunk))
    Y.append(encode(target))

import torch

X = torch.tensor(X, dtype=torch.long)
Y = torch.tensor(Y, dtype=torch.long)

print("X : ", X)
print("Y : ", Y)


X :  tensor([[15, 39, 48,  ..., 36, 51, 48],
        [49, 50,  1,  ..., 50, 38, 35],
        [12, 39, 50,  ..., 48,  4,  1],
        ...,
        [48, 49, 50,  ...,  3, 34,  1],
        [ 1, 51, 44,  ..., 53, 39, 50],
        [48, 45, 45,  ..., 38,  1, 43]])
Y :  tensor([[39, 48, 49,  ..., 51, 48, 50],
        [50,  1, 12,  ..., 38, 35, 48],
        [39, 50, 39,  ...,  4,  1, 38],
        ...,
        [49, 50,  1,  ..., 34,  1, 53],
        [51, 44, 48,  ..., 39, 50, 38],
        [45, 45, 36,  ...,  1, 43, 35]])


In [ ]:
model = RNN(vocab_size, embed_size=32, hidden_size=64)
optimizer = torch.optim.Adam(model.parameters(), lr=0.005)
criterion = nn.CrossEntropyLoss()

batch_size = 128
epochs = 100

for epoch in range(epochs):
    permutation = torch.randperm(X.size(0))
    total_loss = 0

    for i in range(0, X.size(0), batch_size):
        idx = permutation[i:i + batch_size]
        xb = X[idx]
        yb = Y[idx]

        optimizer.zero_grad()
        logits = model(xb)
        loss = criterion(logits.view(-1, vocab_size), yb.view(-1))
        loss.backward()
        optimizer.step()
        total_loss += loss.item()
    if epoch % 10 == 0:
        avg_loss = total_loss / (X.size(0) // batch_size)
        print(f"Epoch {epoch + 1}, Loss: {avg_loss:.4f}")

Epoch 1, Loss: 92.1858
Epoch 11, Loss: 69.3330
Epoch 21, Loss: 67.8817
Epoch 31, Loss: 67.1670
Epoch 41, Loss: 66.8450
Epoch 51, Loss: 66.6165
Epoch 61, Loss: 66.5904
Epoch 71, Loss: 66.3234
Epoch 81, Loss: 66.5497
Epoch 91, Loss: 66.2094


In [24]:
def generate(model, seed_text, length=100):
    model.eval()
    context = torch.tensor([stoi[c] for c in seed_text], dtype=torch.long).unsqueeze(0)

    with torch.no_grad():
        for _ in range(length):
            logits = model(context)
            last_logits = logits[0, -1]
            probs = torch.softmax(last_logits, dim=0)
            next_id = torch.multinomial(probs, num_samples=1).item()

            context = torch.cat([context, torch.tensor([[next_id]])], dim=1)

    return decode(context.squeeze().tolist())

In [27]:
print(generate(model, "First Citizen: ", length=300))

First Citizen: sfeiraS ur ox thte gxbuep eanendre foolrst Chon'ts a mollths kY aaM'n,angrr,hicrupa lire
Bewlohu? si rovusateyngrw langthaltanee ei'elp
Te
utizize a'olyiunselheb workue  fali'elerin eot fibs ansi ce' omeurst you.tore hp dou stouols, aturdite
MENENIUSpygns ouebrtosorr ms
lae fou fea ythns ot JWun blt
